import React, { useState } from 'react';
import { FileText, Download, Trash2 } from 'lucide-react';
import jsPDF from 'jspdf';
import { reportsApi } from '../services/analyticsApi';

const ReportsTable = ({ reports, onDelete, onRefresh }) => {

  const downloadPDF = (report) => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text('TaskMaster - Analytics Report', 20, 20);
    
    // Divider line
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);
    
    // Report details
    doc.setFontSize(12);
    doc.text(`Report Title: ${report.title}`, 20, 35);
    doc.text(`Author: ${report.authorName}`, 20, 45);
    doc.text(`Period: ${report.period}`, 20, 55);
    doc.text(`Status: ${report.status}`, 20, 65);
    doc.text(`Generated: ${new Date(report.generatedAt).toLocaleDateString()}`, 20, 75);
    
    // Data section if exists
    if (report.data) {
      doc.setFontSize(14);
      doc.text('Analytics Summary', 20, 90);
      doc.setFontSize(11);
      doc.text(`Total Tasks: ${report.data.totalTasks || 0}`, 20, 100);
      doc.text(`Completed Tasks: ${report.data.completedTasks || 0}`, 20, 110);
      doc.text(`Productivity: ${report.data.productivity || 0}%`, 20, 120);
    }
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by TaskMaster Reporting & Analytics Service', 20, 280);
    
    doc.save(`${report.title.replace(/\s+/g, '-').toLowerCase()}-report.pdf`);
  };

  const handleDownload = (report) => {
    downloadPDF(report);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const formatTime = (dateString) => {
    return new Date(dateString).toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <div className="bg-[var(--tm-bg-surface)] border border-[var(--tm-border)] rounded-lg p-6">
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-sm font-bold text-white uppercase tracking-wider">Recent Reports</h3>
        <a href="#view-all" className="text-[var(--tm-accent)] hover:text-blue-400 transition text-sm font-medium">
          View All 
        </a>
      </div>

      {reports && reports.length > 0 ? (
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-[var(--tm-border)] text-[var(--tm-text-secondary)] text-xs uppercase tracking-wider font-semibold">
                <th className="text-left py-3 px-4">Report Name</th>
                <th className="text-left py-3 px-4">Date Generated</th>
                <th className="text-left py-3 px-4">Author</th>
                <th className="text-left py-3 px-4">Status</th>
                <th className="text-center py-3 px-4">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr key={report._id} className="border-b border-[var(--tm-border)] hover:bg-white/5 transition">
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <FileText size={15} className="text-[var(--tm-accent)] flex-shrink-0" />
                      <span className="text-white">{report.title}</span>
                    </div>
                  </td>
                  <td className="py-4 px-4 text-slate-300 text-sm">
                    <div>{formatDate(report.generatedAt)}</div>
                    <div className="text-xs text-[var(--tm-text-secondary)]">{formatTime(report.generatedAt)}</div>
                  </td>
                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <div className="w-6 h-6 rounded-full bg-[#144bb8]/20 flex items-center justify-center text-xs font-bold text-[var(--tm-accent)]">
                        {report.authorName?.charAt(0).toUpperCase()}
                      </div>
                      <span className="text-white text-sm">{report.authorName}</span>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <span className={
                      report.status === 'ready' 
                        ? 'px-2.5 py-1 rounded-full text-xs font-medium bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                        : report.status === 'processing'
                        ? 'px-2.5 py-1 rounded-full text-xs font-medium bg-amber-500/20 text-amber-400 border border-amber-500/30'
                        : 'px-2.5 py-1 rounded-full text-xs font-medium bg-orange-500/20 text-orange-400 border border-orange-500/30'
                    }>
                      {report.status === 'ready' ? '✓ Ready' 
                        : report.status === 'processing' ? '⏳ Processing' 
                        : '🕐 Pending'}
                    </span>
                  </td>
                  <td className="py-4 px-4 text-center">
                    <div className="flex items-center gap-2 justify-center">
                      <button onClick={() => downloadPDF(report)}
                        className="p-1.5 text-gray-400 hover:text-blue-400 
                        hover:bg-blue-400/10 rounded-md transition-colors"
                        title="Download PDF">
                        <Download size={15} />
                      </button>
                      <button onClick={() => onDelete(report._id)}
                        className="p-1.5 text-gray-400 hover:text-red-400 
                        hover:bg-red-400/10 rounded-md transition-colors"
                        title="Delete">
                        <Trash2 size={15} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="text-center py-8">
          <p className="text-[var(--tm-text-secondary)]">No reports yet. Generate your first report!</p>
        </div>
      )}
    </div>
  );
};

export default ReportsTable;
